name: flutter_location_wakeup
description: Listens for significant location changes the device and wakes it up when they arrive
version: 0.1.0-beta
repository: https://github.com/MelbourneDeveloper/flutter_location_wakeup

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.13.5'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:  
  austerity: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
 
  plugin:
    platforms:
      ios:
        pluginClass: LocPlugin